In [3]:
#!pip install pandas numpy
# import pandas as pd
# import numpy as np
import bcrypt

In [34]:
std = pd.read_csv('students.csv')
std.tail()

,admission_number,name,date_of_birth,parent_phone,y_o_e,address,password,image,class,results_visible,gender
83,GPT/2026/061,EDEWUSI OKIKI,NaN,NaN,NaN,NaN,123456,NaN,PRIMARY 3,True,NaN
84,GPT/2026/063,OLANIYI OLUWADARASIMI,NaN,NaN,NaN,NaN,123456,NaN,PRIMARY 4,True,NaN
85,GPT/2026/064,TEMITOPE PAMILERIN,NaN,NaN,NaN,NaN,123456,NaN,PRIMARY 4,True,NaN
86,GPT/2026/065,TEMITOPE GBOLAHAN,NaN,NaN,NaN,NaN,123456,NaN,PRIMARY 4,True,NaN
87,GPT/2026/066,ADEWUMI OLUWAFIKAYO,NaN,NaN,NaN,NaN,123456,NaN,PRIMARY 4,True,NaN

In [18]:
std.describe(include='all')

,admission_number,name,date_of_birth,parent_phone,y_o_e,address,password,image,class,results_visible,gender
count,88,88,25,2.500000e+01,29.000000,25,3.400000e+01,0.0,88,88,0.0
unique,88,88,25,NaN,NaN,22,NaN,NaN,14,1,NaN
top,GPT/2018/001,Alaaka Oluwajubelo John,7/18/2013,NaN,NaN,"Bonnke Quarters, Ilesa",NaN,NaN,PRIMARY 3,True,NaN
freq,1,1,1,NaN,NaN,3,NaN,NaN,13,88,NaN
mean,NaN,NaN,NaN,8.011590e+09,2022.793103,NaN,5.890908e+09,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,6.621805e+08,2.042046,NaN,3.631796e+09,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,7.031154e+09,2018.000000,NaN,1.234560e+05,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,8.031539e+09,2020.000000,NaN,1.757881e+09,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,8.067737e+09,2024.000000,NaN,8.033238e+09,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,8.169484e+09,2024.000000,NaN,8.137811e+09,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,9.163891e+09,2025.000000,NaN,9.163891e+09,NaN,NaN,NaN,NaN

In [16]:
# Make all results visible
std['results_visible'] = True

std['results_visible'].value_counts()

results_visible
True    88
Name: count, dtype: int64

In [23]:
# Fill all the passwords with 123456
std.password = std['password'].fillna('123456')

std['password']

0     8169712860.0
1     8138155994.0
2     8169687870.0
3         123456.0
4         123456.0
          ...
83          123456
84          123456
85          123456
86          123456
87          123456
Name: password, Length: 88, dtype: object

In [4]:
def hash_password(plain_password):
    # convert password to bytes
    plain_password_bytes = plain_password.encode('utf-8')
    
    # generate salt
    salt = bcrypt.gensalt()
    
    # hash password
    hashed_bytes = bcrypt.hashpw(plain_password_bytes, salt)
    
    # store as string
    stored_hash = hashed_bytes.decode('utf-8')
    
    return stored_hash

In [11]:
hash_password('123456')

'$2b$12$EmsBItHDvDcczINtTw.OSehUt1gS4lEDMrfB1yhcgzY0pXjrv94mW'

In [35]:
std['password'] = std['password'].astype('str').apply(hash_password)

std['password']

0     $2b$12$16IHY9p/d//3m72Tzsp.2OLMnRy/JCxmu/2yBlg...
1     $2b$12$EkytxZPe4vEGUf/d27/atO5FFOnIpjcW5FPhVZf...
2     $2b$12$E0UCHWXMl8BYeQRVk1JZWe09botAS6TxEAJLINZ...
3     $2b$12$nPPGnZzncrU7DEpxHj1DR.rTOVtdHaTJbxSioGl...
4     $2b$12$qpchRpcm2EK1xkSPoxBYGO/Mxd4rLdURA19O4IK...
                            ...
83    $2b$12$w559M4XkpHgMuZe4WTlkZ.msle5HN6cP3K5kQ53...
84    $2b$12$gpzkfqYPKCt9P.QoGUTju.r8V7MthAyRMMll3Tm...
85    $2b$12$/SoTF8rp3bntqmAA2a/OeOSYgynzVh2m4ocO2Kc...
86    $2b$12$rYKm1rze7bytjE/Ry1aPde6powyn/REnJJrQRNQ...
87    $2b$12$JCHHmdpgen8j4dJRNVU2mOMPR8ridnrvX6TrGKj...
Name: password, Length: 88, dtype: object

In [37]:
std.to_csv('std.csv', index='False')